
# src/labels.py

# GTSRB oficialūs 43 ženklų pavadinimai (0–42)
CLASS_LABELS = {
    0: "Apvalus bendras įspėjamasis ženklas",
    1: "Leistinas greitis 20 km/h",
    2: "Leistinas greitis 30 km/h",
    3: "Leistinas greitis 50 km/h",
    4: "Leistinas greitis 60 km/h",
    5: "Leistinas greitis 70 km/h",
    6: "Leistinas greitis 80 km/h",
    7: "Greitis 80 km/h pabaiga",
    8: "Leistinas greitis 100 km/h",
    9: "Leistinas greitis 120 km/h",
    10: "Lenkti draudžiama",
    11: "Lenkti krovininiams automobiliais draudžiama",
    12: "Pirmumo ženklas",
    13: "Pagrindinis kelias",
    14: "Užleiskite kelią",
    15: "STOP",
    16: "Eismas draudžiamas",
    17: "Įvažiavimas draudžiamas",
    18: "Bendras įspėjamasis ženklas",
    19: "Pavojingas posūkis į kairę",
    20: "Pavojingas posūkis į dešinę",
    21: "Dvigubas posūkis",
    22: "Nelygus kelias",
    23: "Slidus kelias",
    24: "Siauras kelias iš abiejų pusių",
    25: "Kelio darbai",
    26: "Šviesoforas",
    27: "Pėsčiųjų perėja",
    28: "Vaikai kelyje",
    29: "Dviračiai kelyje",
    30: "Sniegas / ledas",
    31: "Gyvūnai kelyje",
    32: "Visų apribojimų pabaiga",
    33: "Privalomas posūkis į dešinę",
    34: "Privalomas posūkis į kairę",
    35: "Privaloma važiuoti tiesiai",
    36: "Privaloma važiuoti tiesiai arba į dešinę",
    37: "Privaloma važiuoti tiesiai arba į kairę",
    38: "Aplenkimas iš dešinės",
    39: "Aplenkimas iš kairės",
    40: "Apvažiavimas ratu",
    41: "Greičio apribojimų pabaiga",
    42: "Lenkimo draudimo pabaiga"
}